/**
 * 由 src/kubernetes/gen/index.ts 自动生成
 * !!! 请不要修改 !!!
 */
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Application is the Schema for the applications API
 */
export interface Application {
  /**
   * APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
   */
  apiVersion?: string;
  /**
   * Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
   */
  kind?: string;
  metadata?: {
    [k: string]: any;
  };
  /**
   * ApplicationSpec defines the desired state of Application
   */
  spec?: {
    appID: string;
    createTime?: string;
    description?: string;
    entryService?: string;
    hostCluster?: string;
    modifyTime?: string;
    module?: number;
    name: string;
    namespace?: string;
    phase?: number;
    relations?: string;
    userID?: number;
    [k: string]: any;
  };
  /**
   * ApplicationStatus defines the observed state of Application
   */
  status?: {
    [k: string]: any;
  };
  [k: string]: any;
}
