/**
 * 由 src/kubernetes/gen/index.ts 自动生成
 * !!! 请不要修改 !!!
 */
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Chaincode {
  /**
   * APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
   */
  apiVersion?: string;
  /**
   * Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
   */
  kind?: string;
  metadata?: {
    [k: string]: any;
  };
  spec?: {
    /**
     * Which channel does chaincode belong to.
     */
    channel: string;
    endorsePolicyRef: {
      name?: string;
      [k: string]: any;
    };
    /**
     * ExternalBuilder used, default is k8s
     */
    externalBuilder: string;
    /**
     * chaincode id
     */
    id?: string;
    /**
     * the image used by the current version of chaincode
     */
    images?: {
      digest: string;
      name: string;
      pullSecret?: string;
      [k: string]: any;
    };
    initRequired: false;
    label?: string;
    /**
     * License should be accepted to install custom resources
     */
    license: {
      /**
       * Accept should be set to true to accept the license.
       */
      accept?: true;
      [k: string]: any;
    };
    /**
     * current version
     */
    version?: string;
    [k: string]: any;
  };
  status?: {
    conditions?: {
      lastTransitionTime?: string;
      message?: string;
      /**
       * if an error occurs, which step to start from
       */
      nextStage?: string;
      reason?: string;
      status?: string;
      type?: string;
      [k: string]: any;
    }[];
    /**
     * Chaincode upgrade history
     */
    history?: {
      externalBuilder: string;
      image: {
        digest: string;
        name: string;
        pullSecret?: string;
        [k: string]: any;
      };
      upgradeTime: string;
      version: string;
      [k: string]: any;
    }[];
    /**
     * LastHeartbeatTime is when the controller reconciled this component
     */
    lastHeartbeatTime?: string;
    message?: string;
    phase?: string;
    reason?: string;
    sequence: number;
    [k: string]: any;
  };
  [k: string]: any;
}
