/**
 * 由 src/kubernetes/gen/index.ts 自动生成
 * !!! 请不要修改 !!!
 */
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * ChaincodeBuild is the Schema for the chaincodebuilds API
 */
export interface ChaincodeBuild {
  /**
   * APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
   */
  apiVersion?: string;
  /**
   * Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
   */
  kind?: string;
  metadata?: {
    [k: string]: any;
  };
  /**
   * ChaincodeBuildSpec defines the desired state of ChaincodeBuild
   */
  spec?: {
    /**
     * Name of the chaincode
     */
    id: string;
    /**
     * Initiator is the organization who initiates this chaincode build
     */
    initiator: string;
    /**
     * License should be accepted by the user to be able to setup console
     */
    license: {
      /**
       * Accept should be set to true to accept the license.
       */
      accept?: true;
      [k: string]: any;
    };
    /**
     * Network of the chaincode belongs to
     */
    network: string;
    /**
     * PipelineRunSpec defines the tekton  pipelinerun which reference pipeline `ChaincodeBuild`
     */
    pipelineRunSpec: {
      dockerBuild: {
        appImage?: string;
        context?: string;
        dockerfile?: string;
        pushSecret?: string;
        [k: string]: any;
      };
      git?: {
        reference?: string;
        url?: string;
        [k: string]: any;
      };
      minio?: {
        accessKey?: string;
        bucket?: string;
        host?: string;
        object?: string;
        secretKey?: string;
        [k: string]: any;
      };
      [k: string]: any;
    };
    /**
     * Version of the chaincode
     */
    version: string;
    [k: string]: any;
  };
  /**
   * ChaincodeBuildStatus defines the observed state of ChaincodeBuild
   */
  status?: {
    /**
     * ErrorCode is the code of classification of errors
     */
    errorcode?: number;
    /**
     * LastHeartbeatTime is when the controller reconciled this component
     */
    lastHeartbeatTime?: string;
    /**
     * Message provides a message for the status to be shown to customer
     */
    message?: string;
    /**
     * PipelineRunResults after pipeline completed
     */
    pipelineResults?: {
      /**
       * Name is the result's name as declared by the Pipeline
       */
      name: string;
      /**
       * Value is the result returned from the execution of this PipelineRun
       */
      value: string;
      [k: string]: any;
    }[];
    /**
     * Reason provides a reason for an error
     */
    reason?: string;
    /**
     * Status is defined based on the current status of the component
     */
    status?: string;
    /**
     * Type is true or false based on if status is valid
     */
    type?: string;
    /**
     * Version is the product (IBP) version of the component
     */
    version?: string;
    /**
     * Versions is the operand version of the component
     */
    versions?: {
      /**
       * Reconciled provides the reconciled version of the operand
       */
      reconciled: string;
      [k: string]: any;
    };
    [k: string]: any;
  };
  [k: string]: any;
}
