/**
 * 由 src/kubernetes/gen/index.ts 自动生成
 * !!! 请不要修改 !!!
 */
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Ordering nodes create the blocks that form the ledger and send them to peers. Warning: Orderer deployment using this tile is not supported. Please use the IBP Console to deploy an orderer.
 */
export interface IBPOrderer {
  /**
   * APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
   */
  apiVersion?: string;
  /**
   * Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
   */
  kind?: string;
  metadata?: {
    [k: string]: any;
  };
  /**
   * IBPOrdererSpec defines the desired state of IBPOrderer
   */
  spec?: {
    /**
     * Action (Optional) is object for orderer actions
     */
    action?: {
      /**
       * Enroll contains actions for triggering crypto enroll
       */
      enroll?: {
        /**
         * Ecert is used to trigger enroll for ecert
         */
        ecert?: boolean;
        /**
         * TLSCert is used to trigger enroll for tls certs
         */
        tlscert?: boolean;
        [k: string]: any;
      };
      /**
       * Reenroll contains actions for triggering crypto reenroll
       */
      reenroll?: {
        /**
         * Ecert is used to trigger reenroll for ecert
         */
        ecert?: boolean;
        /**
         * EcertNewKey is used to trigger reenroll for ecert and also generating a new private key
         */
        ecertNewKey?: boolean;
        /**
         * TLSCert is used to trigger reenroll for tlscert
         */
        tlscert?: boolean;
        /**
         * TLSCertNewKey is used to trigger reenroll for tlscert and also generating a new private key
         */
        tlscertNewKey?: boolean;
        [k: string]: any;
      };
      /**
       * Restart action is used to restart orderer deployment
       */
      restart?: boolean;
      [k: string]: any;
    };
    /**
     * Arch (Optional) is the architecture of the nodes where orderer should be deployed
     */
    arch?: string[];
    /**
     * ClusterSize (Optional) number of orderers if a cluster
     */
    clusterSize?: number;
    /**
     * ClusterConfigOverride (Optional) is array of config overrides for cluster
     */
    clusterconfigoverride?: {
      [k: string]: any;
    }[];
    /**
     * ClusterSecret (Optional) is array of msp crypto for cluster
     */
    clustersecret?: {
      /**
       * Enrollment defines enrollment part of secret spec
       */
      enrollment?: {
        /**
         * ClientAuth contains client uath enrollment details
         */
        clientauth?: {
          /**
           * AdminCerts is the base64 encoded admincerts
           */
          admincerts?: string[];
          /**
           * CAHost is host part of the CA to use
           */
          cahost?: string;
          /**
           * CAName is name of CA
           */
          caname?: string;
          /**
           * CAPort is port of the CA to use
           */
          caport?: string;
          /**
           * CATLS is tls details to talk to CA endpoint
           */
          catls?: {
            /**
             * CACert is the base64 encoded certificate
             */
            cacert?: string;
            [k: string]: any;
          };
          /**
           * CSR is the CSR override object
           */
          csr?: {
            /**
             * Hosts override for CSR
             */
            hosts?: string[];
            [k: string]: any;
          };
          /**
           * EnrollID is the enrollment username
           */
          enrollid?: string;
          /**
           * EnrollSecret is enrollment secret ( password )
           */
          enrollsecret?: string;
          enrolltoken?: string;
          /**
           * IAM auth information. Generally speaking, it is the organization's admin
           */
          enrolluser?: string;
          [k: string]: any;
        };
        /**
         * Component contains ecert enrollment details
         */
        component?: {
          /**
           * AdminCerts is the base64 encoded admincerts
           */
          admincerts?: string[];
          /**
           * CAHost is host part of the CA to use
           */
          cahost?: string;
          /**
           * CAName is name of CA
           */
          caname?: string;
          /**
           * CAPort is port of the CA to use
           */
          caport?: string;
          /**
           * CATLS is tls details to talk to CA endpoint
           */
          catls?: {
            /**
             * CACert is the base64 encoded certificate
             */
            cacert?: string;
            [k: string]: any;
          };
          /**
           * CSR is the CSR override object
           */
          csr?: {
            /**
             * Hosts override for CSR
             */
            hosts?: string[];
            [k: string]: any;
          };
          /**
           * EnrollID is the enrollment username
           */
          enrollid?: string;
          /**
           * EnrollSecret is enrollment secret ( password )
           */
          enrollsecret?: string;
          enrolltoken?: string;
          /**
           * IAM auth information. Generally speaking, it is the organization's admin
           */
          enrolluser?: string;
          [k: string]: any;
        };
        /**
         * TLS contains tls enrollment details
         */
        tls?: {
          /**
           * AdminCerts is the base64 encoded admincerts
           */
          admincerts?: string[];
          /**
           * CAHost is host part of the CA to use
           */
          cahost?: string;
          /**
           * CAName is name of CA
           */
          caname?: string;
          /**
           * CAPort is port of the CA to use
           */
          caport?: string;
          /**
           * CATLS is tls details to talk to CA endpoint
           */
          catls?: {
            /**
             * CACert is the base64 encoded certificate
             */
            cacert?: string;
            [k: string]: any;
          };
          /**
           * CSR is the CSR override object
           */
          csr?: {
            /**
             * Hosts override for CSR
             */
            hosts?: string[];
            [k: string]: any;
          };
          /**
           * EnrollID is the enrollment username
           */
          enrollid?: string;
          /**
           * EnrollSecret is enrollment secret ( password )
           */
          enrollsecret?: string;
          enrolltoken?: string;
          /**
           * IAM auth information. Generally speaking, it is the organization's admin
           */
          enrolluser?: string;
          [k: string]: any;
        };
        [k: string]: any;
      };
      /**
       * MSP defines msp part of secret spec
       */
      msp?: {
        /**
         * ClientAuth contains crypto for client auth certs
         */
        clientauth?: {
          /**
           * AdminCerts is base64 encoded admincerts array
           */
          admincerts?: string[];
          /**
           * CACerts is base64 encoded cacerts array
           */
          cacerts?: string[];
          /**
           * IntermediateCerts is base64 encoded intermediate certs array
           */
          intermediatecerts?: string[];
          /**
           * KeyStore is base64 encoded private key
           */
          keystore?: string;
          /**
           * SignCerts is base64 encoded sign cert
           */
          signcerts?: string;
          [k: string]: any;
        };
        /**
         * Component contains crypto for ecerts
         */
        component?: {
          /**
           * AdminCerts is base64 encoded admincerts array
           */
          admincerts?: string[];
          /**
           * CACerts is base64 encoded cacerts array
           */
          cacerts?: string[];
          /**
           * IntermediateCerts is base64 encoded intermediate certs array
           */
          intermediatecerts?: string[];
          /**
           * KeyStore is base64 encoded private key
           */
          keystore?: string;
          /**
           * SignCerts is base64 encoded sign cert
           */
          signcerts?: string;
          [k: string]: any;
        };
        /**
         * TLS contains crypto for tls certs
         */
        tls?: {
          /**
           * AdminCerts is base64 encoded admincerts array
           */
          admincerts?: string[];
          /**
           * CACerts is base64 encoded cacerts array
           */
          cacerts?: string[];
          /**
           * IntermediateCerts is base64 encoded intermediate certs array
           */
          intermediatecerts?: string[];
          /**
           * KeyStore is base64 encoded private key
           */
          keystore?: string;
          /**
           * SignCerts is base64 encoded sign cert
           */
          signcerts?: string;
          [k: string]: any;
        };
        [k: string]: any;
      };
      [k: string]: any;
    }[];
    /**
     * ConfigOverride (Optional) is the object to provide overrides to core yaml config
     */
    configoverride?: {
      [k: string]: any;
    };
    /**
     * CustomNames (Optional) is to use pre-configured resources for orderer's deployment
     */
    customNames?: {
      /**
       * PVC is the list of PVC Names to be used for orderer's deployment
       */
      pvc?: {
        /**
         * Orderer is the pvc to be used as orderer's storage
         */
        orderer?: string;
        [k: string]: any;
      };
      [k: string]: any;
    };
    /**
     * DisableNodeOU (Optional) is used to switch nodeou on and off
     */
    disablenodeou?: boolean;
    /**
     * Domain is the sub-domain used for orderer's deployment
     */
    domain?: string;
    /**
     * ExternalAddress (Optional) is used internally
     */
    externalAddress?: string;
    /**
     * GenesisBlock (Optional) is genesis block to start the orderer
     */
    genesisBlock?: string;
    genesisProfile?: string;
    /**
     * HSM (Optional) is DEPRECATED
     */
    hsm?: {
      /**
       * PKCS11Endpoint is DEPRECATED
       */
      pkcs11endpoint?: string;
      [k: string]: any;
    };
    /**
     * ImagePullSecrets (Optional) is the list of ImagePullSecrets to be used for orderer's deployment
     */
    imagePullSecrets?: string[];
    /**
     * Images (Optional) lists the images to be used for orderer's deployment
     */
    images?: {
      /**
       * EnrollerImage is the name of the init image for crypto generation
       */
      enrollerImage?: string;
      /**
       * EnrollerTag is the tag of the init image for crypto generation
       */
      enrollerTag?: string;
      /**
       * GRPCWebImage is the name of the grpc web proxy image
       */
      grpcwebImage?: string;
      /**
       * GRPCWebTag is the tag of the grpc web proxy image
       */
      grpcwebTag?: string;
      /**
       * HSMImage is the name of the hsm image
       */
      hsmImage?: string;
      /**
       * HSMTag is the tag of the hsm image
       */
      hsmTag?: string;
      /**
       * OrdererImage is the name of the orderer image
       */
      ordererImage?: string;
      /**
       * OrdererInitImage is the name of the orderer init image
       */
      ordererInitImage?: string;
      /**
       * OrdererInitTag is the tag of the orderer init image
       */
      ordererInitTag?: string;
      /**
       * OrdererTag is the tag of the orderer image
       */
      ordererTag?: string;
      [k: string]: any;
    };
    /**
     * Ingress (Optional) is ingress object for ingress overrides
     */
    ingress?: {
      /**
       * Class (Optional) is the class to set for ingress
       */
      class?: string;
      /**
       * TlsSecretName (Optional) is the secret name to be used for tls certificates
       */
      tlsSecretName?: string;
      [k: string]: any;
    };
    /**
     * IsPrecreate (Optional) defines if orderer is in precreate state
     */
    isprecreate?: boolean;
    /**
     * License should be accepted by the user to be able to setup orderer
     */
    license: {
      /**
       * Accept should be set to true to accept the license.
       */
      accept?: true;
      [k: string]: any;
    };
    /**
     * ClusterLocation (Optional) is array of cluster location settings for cluster
     */
    location?: {
      /**
       * Region (Optional) is the region of the nodes where the orderer should be deployed
       */
      region?: string;
      /**
       * Zone (Optional) is the zone of the nodes where the orderer should be deployed
       */
      zone?: string;
      [k: string]: any;
    }[];
    /**
     * MSPID is the msp id of the orderer
     */
    mspID?: string;
    /**
     * NumSecondsWarningPeriod (Optional - default 30 days) is used to define certificate expiry warning period.
     */
    numSecondsWarningPeriod?: number;
    /**
     * NodeNumber (Optional) is the number of this node in cluster - used internally
     */
    number?: number;
    /**
     * OrdererType is type of orderer you want to start
     */
    ordererType?: string;
    /**
     * OrgName is the organization name of the orderer
     */
    orgName?: string;
    /**
     * Region (Optional) is the region of the nodes where the orderer should be deployed
     */
    region?: string;
    /**
     * RegistryURL is registry url used to pull images
     */
    registryURL?: string;
    /**
     * Replicas (Optional - default 1) is the number of orderer replicas to be setup
     */
    replicas?: number;
    /**
     * Resources (Optional) is the amount of resources to be provided to orderer deployment
     */
    resources?: {
      /**
       * Enroller (Optional) is the resources provided to the enroller container
       */
      enroller?: {
        /**
         * Limits describes the maximum amount of compute resources allowed. More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
         */
        limits?: {
          [k: string]: number | string;
        };
        /**
         * Requests describes the minimum amount of compute resources required. If Requests is omitted for a container, it defaults to Limits if that is explicitly specified, otherwise to an implementation-defined value. More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
         */
        requests?: {
          [k: string]: number | string;
        };
        [k: string]: any;
      };
      /**
       * HSMDaemon (Optional) is the resources provided to the HSM Daemon container
       */
      hsmdaemon?: {
        /**
         * Limits describes the maximum amount of compute resources allowed. More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
         */
        limits?: {
          [k: string]: number | string;
        };
        /**
         * Requests describes the minimum amount of compute resources required. If Requests is omitted for a container, it defaults to Limits if that is explicitly specified, otherwise to an implementation-defined value. More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
         */
        requests?: {
          [k: string]: number | string;
        };
        [k: string]: any;
      };
      /**
       * Init (Optional) is the resources provided to the init container
       */
      init?: {
        /**
         * Limits describes the maximum amount of compute resources allowed. More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
         */
        limits?: {
          [k: string]: number | string;
        };
        /**
         * Requests describes the minimum amount of compute resources required. If Requests is omitted for a container, it defaults to Limits if that is explicitly specified, otherwise to an implementation-defined value. More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
         */
        requests?: {
          [k: string]: number | string;
        };
        [k: string]: any;
      };
      /**
       * Orderer (Optional) is the resources provided to the orderer container
       */
      orderer?: {
        /**
         * Limits describes the maximum amount of compute resources allowed. More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
         */
        limits?: {
          [k: string]: number | string;
        };
        /**
         * Requests describes the minimum amount of compute resources required. If Requests is omitted for a container, it defaults to Limits if that is explicitly specified, otherwise to an implementation-defined value. More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
         */
        requests?: {
          [k: string]: number | string;
        };
        [k: string]: any;
      };
      /**
       * GRPCProxy (Optional) is the resources provided to the proxy container
       */
      proxy?: {
        /**
         * Limits describes the maximum amount of compute resources allowed. More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
         */
        limits?: {
          [k: string]: number | string;
        };
        /**
         * Requests describes the minimum amount of compute resources required. If Requests is omitted for a container, it defaults to Limits if that is explicitly specified, otherwise to an implementation-defined value. More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
         */
        requests?: {
          [k: string]: number | string;
        };
        [k: string]: any;
      };
      [k: string]: any;
    };
    /**
     * Secret is object for msp crypto
     */
    secret?: {
      /**
       * Enrollment defines enrollment part of secret spec
       */
      enrollment?: {
        /**
         * ClientAuth contains client uath enrollment details
         */
        clientauth?: {
          /**
           * AdminCerts is the base64 encoded admincerts
           */
          admincerts?: string[];
          /**
           * CAHost is host part of the CA to use
           */
          cahost?: string;
          /**
           * CAName is name of CA
           */
          caname?: string;
          /**
           * CAPort is port of the CA to use
           */
          caport?: string;
          /**
           * CATLS is tls details to talk to CA endpoint
           */
          catls?: {
            /**
             * CACert is the base64 encoded certificate
             */
            cacert?: string;
            [k: string]: any;
          };
          /**
           * CSR is the CSR override object
           */
          csr?: {
            /**
             * Hosts override for CSR
             */
            hosts?: string[];
            [k: string]: any;
          };
          /**
           * EnrollID is the enrollment username
           */
          enrollid?: string;
          /**
           * EnrollSecret is enrollment secret ( password )
           */
          enrollsecret?: string;
          enrolltoken?: string;
          /**
           * IAM auth information. Generally speaking, it is the organization's admin
           */
          enrolluser?: string;
          [k: string]: any;
        };
        /**
         * Component contains ecert enrollment details
         */
        component?: {
          /**
           * AdminCerts is the base64 encoded admincerts
           */
          admincerts?: string[];
          /**
           * CAHost is host part of the CA to use
           */
          cahost?: string;
          /**
           * CAName is name of CA
           */
          caname?: string;
          /**
           * CAPort is port of the CA to use
           */
          caport?: string;
          /**
           * CATLS is tls details to talk to CA endpoint
           */
          catls?: {
            /**
             * CACert is the base64 encoded certificate
             */
            cacert?: string;
            [k: string]: any;
          };
          /**
           * CSR is the CSR override object
           */
          csr?: {
            /**
             * Hosts override for CSR
             */
            hosts?: string[];
            [k: string]: any;
          };
          /**
           * EnrollID is the enrollment username
           */
          enrollid?: string;
          /**
           * EnrollSecret is enrollment secret ( password )
           */
          enrollsecret?: string;
          enrolltoken?: string;
          /**
           * IAM auth information. Generally speaking, it is the organization's admin
           */
          enrolluser?: string;
          [k: string]: any;
        };
        /**
         * TLS contains tls enrollment details
         */
        tls?: {
          /**
           * AdminCerts is the base64 encoded admincerts
           */
          admincerts?: string[];
          /**
           * CAHost is host part of the CA to use
           */
          cahost?: string;
          /**
           * CAName is name of CA
           */
          caname?: string;
          /**
           * CAPort is port of the CA to use
           */
          caport?: string;
          /**
           * CATLS is tls details to talk to CA endpoint
           */
          catls?: {
            /**
             * CACert is the base64 encoded certificate
             */
            cacert?: string;
            [k: string]: any;
          };
          /**
           * CSR is the CSR override object
           */
          csr?: {
            /**
             * Hosts override for CSR
             */
            hosts?: string[];
            [k: string]: any;
          };
          /**
           * EnrollID is the enrollment username
           */
          enrollid?: string;
          /**
           * EnrollSecret is enrollment secret ( password )
           */
          enrollsecret?: string;
          enrolltoken?: string;
          /**
           * IAM auth information. Generally speaking, it is the organization's admin
           */
          enrolluser?: string;
          [k: string]: any;
        };
        [k: string]: any;
      };
      /**
       * MSP defines msp part of secret spec
       */
      msp?: {
        /**
         * ClientAuth contains crypto for client auth certs
         */
        clientauth?: {
          /**
           * AdminCerts is base64 encoded admincerts array
           */
          admincerts?: string[];
          /**
           * CACerts is base64 encoded cacerts array
           */
          cacerts?: string[];
          /**
           * IntermediateCerts is base64 encoded intermediate certs array
           */
          intermediatecerts?: string[];
          /**
           * KeyStore is base64 encoded private key
           */
          keystore?: string;
          /**
           * SignCerts is base64 encoded sign cert
           */
          signcerts?: string;
          [k: string]: any;
        };
        /**
         * Component contains crypto for ecerts
         */
        component?: {
          /**
           * AdminCerts is base64 encoded admincerts array
           */
          admincerts?: string[];
          /**
           * CACerts is base64 encoded cacerts array
           */
          cacerts?: string[];
          /**
           * IntermediateCerts is base64 encoded intermediate certs array
           */
          intermediatecerts?: string[];
          /**
           * KeyStore is base64 encoded private key
           */
          keystore?: string;
          /**
           * SignCerts is base64 encoded sign cert
           */
          signcerts?: string;
          [k: string]: any;
        };
        /**
         * TLS contains crypto for tls certs
         */
        tls?: {
          /**
           * AdminCerts is base64 encoded admincerts array
           */
          admincerts?: string[];
          /**
           * CACerts is base64 encoded cacerts array
           */
          cacerts?: string[];
          /**
           * IntermediateCerts is base64 encoded intermediate certs array
           */
          intermediatecerts?: string[];
          /**
           * KeyStore is base64 encoded private key
           */
          keystore?: string;
          /**
           * SignCerts is base64 encoded sign cert
           */
          signcerts?: string;
          [k: string]: any;
        };
        [k: string]: any;
      };
      [k: string]: any;
    };
    /**
     * Service (Optional) is the override object for orderer's service
     */
    service?: {
      /**
       * The "type" of the service to be used
       */
      type?: string;
      [k: string]: any;
    };
    /**
     * Storage (Optional - uses default storageclass if not provided) is the override object for CA's PVC config
     */
    storage?: {
      /**
       * Orderer (Optional) is the configuration of the storage of the orderer
       */
      orderer?: {
        /**
         * Class is the storage class
         */
        class?: string;
        /**
         * Size of storage
         */
        size?: string;
        [k: string]: any;
      };
      [k: string]: any;
    };
    /**
     * SystemChannelName is the name of systemchannel
     */
    systemChannelName?: string;
    useChannelLess?: boolean;
    /**
     * FabricVersion (Optional) is fabric version for the orderer
     */
    version?: string;
    /**
     * Zone (Optional) is the zone of the nodes where the orderer should be deployed
     */
    zone?: string;
    [k: string]: any;
  };
  /**
   * IBPOrdererStatus defines the observed state of IBPOrderer
   */
  status?: {
    /**
     * ErrorCode is the code of classification of errors
     */
    errorcode?: number;
    /**
     * LastHeartbeatTime is when the controller reconciled this component
     */
    lastHeartbeatTime?: string;
    /**
     * Message provides a message for the status to be shown to customer
     */
    message?: string;
    /**
     * Reason provides a reason for an error
     */
    reason?: string;
    /**
     * Status is defined based on the current status of the component
     */
    status?: string;
    /**
     * Type is true or false based on if status is valid
     */
    type?: string;
    /**
     * Version is the product (IBP) version of the component
     */
    version?: string;
    /**
     * Versions is the operand version of the component
     */
    versions?: {
      /**
       * Reconciled provides the reconciled version of the operand
       */
      reconciled: string;
      [k: string]: any;
    };
    [k: string]: any;
  };
  [k: string]: any;
}
